start of numpy 


In [1]:
import numpy as np 

In [2]:
arr_1 = np.array([1,2,3,4,5])
print(arr_1)
arr_2 = np.array([[1,2,3],[4,5,6]])
print(arr_2)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


In [3]:
import time 
import numpy as np 
start = time.time()
py_list=[i * 2 for i in range(1000000)]
print(time.time()-start)
start = time.time()
numpy_array = np.arange(1000000) * 2
print(time.time()-start)


0.13612818717956543
0.011438846588134766


#creating array from scratch 

In [4]:
zeros = np.zeros((3,4))
print (zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [5]:
ones = np.ones((2,3,4))
print(ones)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [6]:
full = np.full((2,3),7)
print(full)

[[7 7 7]
 [7 7 7]]


In [7]:
new = np.random.random((2,2))
print(new * 100)



[[16.66632975 47.62153563]
 [85.38191347 66.54897984]]


In [8]:
s1 = np.arange(0,10,2)
s2 = np.arange(0,10,2)
print(s1,s2)



[0 2 4 6 8] [0 2 4 6 8]


#vector , matrix  & tensor 

In [9]:
vector = np.array([1,2,3,4,5])
print("vector : ",vector)
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :\n",matrix)
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[3,4]]])
print("Tensor : \n ",tensor)

vector :  [1 2 3 4 5]
Matrix :
 [[1 2 3]
 [4 5 6]]
Tensor : 
  [[[1 2]
  [3 4]]

 [[5 6]
  [3 4]]]


#array properties

In [ ]:
arr = np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,9,10,11,12]])
print("shape : ",arr.shape)
print("Dimensions : ",arr.ndim)
print("Size  : ",arr.size)
print("Data Type : "  ,arr.dtype)
print("item Size : ",arr.itemsize)
print("Type : ",type(arr))
print("Reshape : ",arr.reshape(4,4))
print("Flattening : ",arr.flatten())# it works on the original array
print("Ravel: ",arr.ravel())# it works on a view\copy of the original array  
print("Transpose array : ",arr.T) 


shape :  (2, 8)
Dimensions :  2
Size  :  16
Data Type :  int64
item Size :  8
Type :  <class 'numpy.ndarray'>
Reshape :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattening :  [ 1  2  3  4  5  6  7  8  5  6  7  8  9 10 11 12]
Ravel:  [ 1  2  3  4  5  6  7  8  5  6  7  8  9 10 11 12]
Transpose array :  [[ 1  5]
 [ 2  6]
 [ 3  7]
 [ 4  8]
 [ 5  9]
 [ 6 10]
 [ 7 11]
 [ 8 12]]
