start of numpy 


In [1]:
import numpy as np 

In [ ]:
# array means a list of numbers and a matrix is a list of lists
arr_1 = np.array([1,2,3,4,5])
print(arr_1)
print(arr_1.T,end='\n\n')

arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)
print(arr_2.T,end='\n\n')

arr_3 =np.array([[1,2],[3,4],[5,6]]) 
print(arr_3)
print(arr_3.T) # .T rows=columns and columns=rows (2,3)(rows=2,columns=3)= (3,2)(rows=3,columns=2) 

[1 2 3 4 5]
[1 2 3 4 5]



AttributeError: 'list' object has no attribute 'T'

In [59]:
import time 
import numpy as np 
start = time.time()  
py_list=[i * 2 for i in range(100000)]
print("list time :",time.time()-start) 
start = time.time()
numpy_array = np.arange(100000) * 2
print("Array time: ", time.time()-start)


list time : 0.009870290756225586
Array time:  0.0011382102966308594


#creating array from scratch 

In [4]:
zeros = np.zeros((3,4))
print (zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [66]:
ones = np.ones((2,3,4))
print(ones)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [70]:
full = np.full((2,3),9)
print(full)

[[9 9 9]
 [9 9 9]]


In [7]:
new = np.random.random((2,2))
print(new * 100)



[[16.66632975 47.62153563]
 [85.38191347 66.54897984]]


In [8]:
s1 = np.arange(0,10,2)
s2 = np.arange(0,10,2)
print(s1,s2)



[0 2 4 6 8] [0 2 4 6 8]


#vector , matrix  & tensor 

In [9]:
vector = np.array([1,2,3,4,5])
print("vector : ",vector)
matrix = np.array([[1,2,3],
                   [4,5,6]])
print("Matrix :\n",matrix)
tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[3,4]]])
print("Tensor : \n ",tensor)

vector :  [1 2 3 4 5]
Matrix :
 [[1 2 3]
 [4 5 6]]
Tensor : 
  [[[1 2]
  [3 4]]

 [[5 6]
  [3 4]]]


#array properties

In [ ]:
arr = np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,9,10,11,12]])
print("shape : ",arr.shape)
print("Dimensions : ",arr.ndim)
print("Size  : ",arr.size)
print("Data Type : "  ,arr.dtype)
print("item Size : ",arr.itemsize)
print("Type : ",type(arr))
print("Reshape : ",arr.reshape(4,4))
print("Flattening : ",arr.flatten())# it works on the original array
print("Ravel: ",arr.ravel())# it works on a view\copy of the original array  
print("Transpose array : ",arr.T) 


shape :  (2, 8)
Dimensions :  2
Size  :  16
Data Type :  int64
item Size :  8
Type :  <class 'numpy.ndarray'>
Reshape :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Flattening :  [ 1  2  3  4  5  6  7  8  5  6  7  8  9 10 11 12]
Ravel:  [ 1  2  3  4  5  6  7  8  5  6  7  8  9 10 11 12]
Transpose array :  [[ 1  5]
 [ 2  6]
 [ 3  7]
 [ 4  8]
 [ 5  9]
 [ 6 10]
 [ 7 11]
 [ 8 12]]
