In [2]:
import numpy as np

# Basic Slicing

In [3]:
arr = np.arange(1,11)
#in slicing the intial number is removed
print("Basic Slicing : ", arr[2:7] ) 
print("Slicing With Step : ",arr[2:7:2])
print("Negative Slicing : ",arr[-3])

Basic Slicing :  [3 4 5 6 7]
Slicing With Step :  [3 5 7]
Negative Slicing :  8


# Slicing in 2-D array

In [6]:
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr_2d)
print("Specific Element :",arr_2d[0,2])
# here [0:,2] 0 th , 1st ,2nd so 2nd is not taken
print("Entire Row :",arr_2d[0:2])
print("Entire Two Row :",arr_2d[0])
print("First Column : ",arr_2d[:,0])
print("Entire Column : ",arr_2d[:,0:])
print("Entire Two Column : ",arr_2d[:,0:2])
'''here arr_2d[0:2,1:3]) [0:2]-stands for first 2 rows [1:3] - stands for the 2nd
 and 3rd column of that of those rows'''
print("Sub-Matrix : ",arr_2d[0:2,1:3])
print("Sub-Matrix : ",arr_2d[::2,::2])


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Specific Element : 3
Entire Row : [[1 2 3 4]
 [5 6 7 8]]
Entire Two Row : [1 2 3 4]
First Column :  [1 5 9]
Entire Column :  [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Entire Two Column :  [[ 1  2]
 [ 5  6]
 [ 9 10]]
Sub-Matrix :  [[2 3]
 [6 7]]
Sub-Matrix :  [[ 1  3]
 [ 9 11]]


# Sorting 

In [5]:
unsorted = np.array([3,5,3,2,1,23,4,6,7,8,9])
# sorting in vector
print("Sorted Array : ",np.sort(unsorted))

Sorted Array :  [ 1  2  3  3  4  5  6  7  8  9 23]


In [ ]:
#sorting in 2D array
arr_2d = np.array([[3,1],[9,4],[5,7]])
print("Sorting in the Column : ",np.sort(arr_2d,axis=0)) # for column sorting
print("Sorting in the Row : ",np.sort(arr_2d,axis=1)) # for row sorting

Sorting in the Column :  [[3 1]
 [5 4]
 [9 7]]
Sorting in the Row :  [[1 3]
 [4 9]
 [5 7]]


# Filtering

In [8]:
num = np.arange(1,11)
print(num)
even_num = num[num % 2 == 0]
print(even_num)
odd_num = num[num % 2 != 0]
print(odd_num)

[ 1  2  3  4  5  6  7  8  9 10]
[ 2  4  6  8 10]
[1 3 5 7 9]


In [9]:
mask = num > 5
print("Number Greater than 5 : ",num[mask])

Number Greater than 5 :  [ 6  7  8  9 10]


#Fancy indexing vs np.where()


In [25]:
indices =[0,2,4]
print(num[indices])
indice = np.where(num>2,num,num)
print(indice)

[1 3 5]
[ 1  2  3  4  5  6  7  8  9 10]


Think of np.where(condition, x, y) like a fork in the road for every single number in your list. 1.3.2, 1.3.5

Here is how it works step-by-step:

The Condition (num > 2): It looks at each number and asks, "Is this bigger than 2?" 1.3.1

The "Yes" Choice (the first num): If the answer is True, it keeps the original number. 1.3.6

The "No" Choice (the second num): If the answer is False, it still keeps the original number. 1.3.6

Because you told it to pick num no matter what, your final indice will look 
exactly like your original array. 1.4.1

Common Ways to Use It:

Usually, people use this to replace values. For example: 
Replace with 0: np.where(num > 2, num, 0)
(If > 2 keep it, otherwise make it 0) 1.3.6

Find positions: np.where(num > 2)
(Just gives you the location/index of the numbers) 1.3.6



In [27]:
replace=np.where(num > 2,num,0)
print(replace)

[ 0  0  3  4  5  6  7  8  9 10]


### Adding and removing data

In [3]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])
arr3= np.array([11,12,13,14,15])
print("compatiblity",arr1.shape == arr2.shape)
combined = np.concatenate([arr1,arr2])
print(combined)
add = np.add(arr1,arr2)
print(add)

sub = np.subtract(arr1,arr2)
print(sub)

mul = np.multiply(arr1,arr2)
print(mul)

divide = np.divide(arr1,arr2)
print(divide)



compatiblity True
[ 1  2  3  4  5  6  7  8  9 10]
[ 7  9 11 13 15]
[-5 -5 -5 -5 -5]
[ 6 14 24 36 50]
[0.16666667 0.28571429 0.375      0.44444444 0.5       ]


In [11]:
original = np.array([[1,2,3],[4,5,6]])
print(original)

new_row  = np.array([7,8,9])
new_col  = np.array([[10,11,12],[13,14,15]])

with_new_row = np.vstack((original,new_row))
print(with_new_row)

with_new_col = np.hstack((original,new_col))
print(with_new_col)

[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  2  3 10 11 12]
 [ 4  5  6 13 14 15]]


In [15]:
arr = np.array([1,2,3,4,5])

deleted = np.delete(arr,2)
print("arrary deleted :",deleted)



arrary deleted : [1 2 4 5]
