# advance arrary operations


In [5]:
import numpy as np
import matplotlib.pyplot as plt


In [11]:
# data of sales (restaurants_id ,2021,2022,2023,2024 )
sales_data = np.array([[1,"MCD",10000,12000,15000,20000], 
                        [2,"pizza hut",12000,13000,14000,21000],
                        [3,"dominos",15000,14000,15000,22000], 
                        [4,"burger king",13000,14000,16000,23000], 
                        [5,"subway",15000,16000,17000,24000], 
                        [6,"popeyes",16000,17000,18000,25000] 
                    ]) 


In [ ]:
print("===== Array Operations =====")

print("Sales Data Shape :",sales_data.shape)

print("Sales of 1st three restaurants : ",sales_data[:3,2:])

print("Total Sales per year : ",np.sum(sales_data[:,2:].astype(int),axis=0))

for i in range(sales_data.shape[0]):
    print(" %s : %s " %(sales_data[i,1],np.sum(sales_data[i,2:].astype(int))))
    print(" {} : {}".format(sales_data[i,1],np.min(sales_data[i,2:].astype(int))))

print("Total Sales till Date : ",np.sum(np.sum(sales_data[:,2:].astype(int))))

In [ ]:
for i in range(sales_data.shape[0]):
    print("{}  : {}".format(sales_data[i,1],sum(sales_data[i,2:].astype(int))))

In [ ]:
data = np.loadtxt('data.csv', delimiter=',')
row_sum = np.sum(data,axis=1)
print(row_sum/data.shape[0])
# loadtxt is uesd to read the data from the file which only has numeric Values , it cannot hanndel null vales 
# delimiter is used to seperate the values in the file
# skiprows=1 is used to skip the first row in the file 
# axis=1 is used to sum the values in the rows , axis = 0 is used to sum the values in the columns axis


In [ ]:
data = np.genfromtxt('employee.csv', delimiter=',',names=True, dtype=None,filling_values='john')
print(data)
mask = data["age"] < 25
print(data[mask])
print(data[~mask])
#names=True is ued to get the column names
#dtype=None is used to get the data type
#encoding is used to specify the encoding of the file



In [ ]:
max =np.max(sales_data[:,2:].astype(int),axis=0)
print(max)

In [ ]:
avg = np.average(sales_data[:,2:].astype(int),axis=1)
print(avg)

cum = np.cumsum(sales_data[:,2:].astype(int),axis=0)
print(cum)


In [ ]:
years=[2021,2022,2023,2024]
plt.figure(figsize=(10,6))
plt.plot(np.mean(cum,axis=0))
plt.title("Average cumulative sales across  all resturant")
plt.xlabel("Years")
plt.ylabel("Sales")
plt.grid(True)
plt.show()

In [ ]:

sales = sales_data[:,2:].astype(int)
years = [2021,2022,2023,2024]
plt.figure(figsize=(10,6))
plt.plot(years,sales.T,marker="o")
plt.title("Best Performing restaurant")
plt.xlabel("Years")
plt.ylabel("Sales")
plt.xticks(years)
plt.legend(sales_data[:,1],title="Restaurant",loc="upper left",bbox_to_anchor=(1,1))
plt.grid(True,linestyle="--",alpha=0.6)
plt.tight_layout()
plt.show()


In [ ]:
import matplotlib.pyplot as plt
import numpy as np

# 1. Define data
sales_data = np.array([[1,"MCD",10000,12000,15000,20000], 
                        [2,"pizza hut",12000,13000,14000,21000],
                        [3,"dominos",15000,14000,15000,22000], 
                        [4,"burger king",13000,14000,16000,23000], 
                        [5,"subway",15000,16000,17000,24000], 
                        [6,"popeyes",16000,17000,18000,25000] 
                    ])

# 2. Extract Years (X-axis) and Sales (Y-axis)
years = [2021, 2022, 2023, 2024]
# Slice all rows, columns from index 2 onwards, and convert to int
sales_values = sales_data[:, 2:].astype(int)
# Extract restaurant names for the legend
restaurant_names = sales_data[:, 1]

# 3. Plotting
plt.figure(figsize=(10, 6))

# Transpose sales_values (.T) because plt.plot() plots each COLUMN as a line
# Here, each row is a restaurant, so transposing makes each restaurant a column
plt.plot(years, sales_values.T, marker='o')

# 4. Customisation
plt.title("Sales Performance by Restaurant (2021-2024)")
plt.xlabel("Year")
plt.ylabel("Sales")
plt.xticks(years) # Ensure only the specific years show on X-axis
plt.legend(restaurant_names, title="Restaurants", bbox_to_anchor=(1.05, 1), loc='upper left')
plt.grid(True, linestyle='--', alpha=0.6)
plt.tight_layout() # Prevents legend from being cut off

plt.show()


In [ ]:
sales_2024 = sales_data[:,2].astype(int)
restaurant_names =sales_data[:,1]
plt.bar(restaurant_names, sales_2024) 
plt.xlabel('Restaurant Name')
plt.ylabel('Sales in 2024')
plt.title('2024 Sales accross all the Restaurant ')
plt.tight_layout()
plt.show()

# vector operations

vector addition

In [5]:
vector1 = np.array([[1,2,3],[4,5,6],[7,8,9]])
vector2 = np.array([[3,2,1],[6,2,6],[10,8,9]])
#addition 
print(vector1+vector2)
#subtraction
print(vector1-vector2)
#multiplication
print(vector1*vector2)
#division
print(vector1/vector2)
#dot product
print(np.dot(vector1,vector2))
#cross product
print(np.cross(vector1,vector2))

angel = np.arccos(np.dot(vector1,vector2)/(np.linalg.norm(vector1)*np.linalg.norm(vector2)))
print(angel)



[[ 4  4  4]
 [10  7 12]
 [17 16 18]]
[[-2  0  2]
 [-2  3  0]
 [-3  0  0]]
[[ 3  4  3]
 [24 10 36]
 [70 64 81]]
[[0.33333333 1.         3.        ]
 [0.66666667 2.5        1.        ]
 [0.7        1.         1.        ]]
[[ 45  30  40]
 [102  66  88]
 [159 102 136]]
[[ -4   8  -4]
 [ 18  12 -22]
 [  0  27 -24]]
[[1.42464089 1.47355271 1.4409781 ]
 [1.23437891 1.35553888 1.28200001]
 [1.03027942 1.23437891 1.11503809]]


In [16]:
restaurant_names = np.array(['McDonalds', 'Burger King', 'KFC', 'Taco Bell', 'Wendy\'s'])
print(restaurant_names)

vectorized = np.vectorize(str.upper)
print(vectorized(restaurant_names))

monthly_avg = sales_data[:,2:].astype(int).mean(axis=1)
print(monthly_avg)

['McDonalds' 'Burger King' 'KFC' 'Taco Bell' "Wendy's"]
['MCDONALDS' 'BURGER KING' 'KFC' 'TACO BELL' "WENDY'S"]
[14250. 15000. 16500. 16500. 18000. 19000.]


In [17]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([[10],[20]])

print(a,b)
print(a + b)


[[1 2 3]
 [4 5 6]] [[10]
 [20]]
[[11 12 13]
 [24 25 26]]


# Broadcasting

In [ ]:
''' Broadcasting works from right to left 
means the dimensions of the arrays should be in the same order 
or either be 1 
eg (2,3) and (3,2) are valid
(2,3) and (1,3)  is valid 
if (2,3) and (3,1) it read it as (1,3)
but (2,4)  and (4,4) is not valid ''' 

' Broadcasting works from right to left \nmeans the dimensions of the arrays should be in the same order \nor either be 1 \neg (2,3) and (3,2) are valid\n(2,3) and (1,3)  is valid \nif (2,3) and (3,1) is there make it transpose (1,3) then it is valid \nbut (2,4)  and (4,4) is not valid '

In [26]:
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[4,5,6],[7,8,9]])
print(a.shape)
print(c.shape)
print(a+c)




(2, 3)
(2, 3)
[[ 5  7  9]
 [11 13 15]]
