start of numpy 


In [2]:
import numpy as np 

In [ ]:
# array means a list of numbers and a matrix is a list of lists
arr_1 = np.array([1,2,3,4,5])
print(arr_1)
print(arr_1.T,end='\n\n')

arr_2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr_2)
print(arr_2.T,end='\n\n')

arr_3 =np.array([[1,2],[3,4],[5,6]]) 
print(arr_3)
print(arr_3.T) # .T rows=columns and columns=rows (2,3)(rows=2,columns=3)= (3,2)(rows=3,columns=2) 

In [ ]:
import time 
import numpy as np 
start = time.time()  
py_list=[i * 2 for i in range(100000)]
print("list time :",time.time()-start) 
start = time.time()
numpy_array = np.arange(100000) * 2
print("Array time: ", time.time()-start)


#creating array from scratch 

In [ ]:
zeros = np.zeros((3,4))
print (zeros)

In [4]:
ones = np.ones((2,3,4))
print(ones)


[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
full = np.full((2,3),9)
print(full)

In [ ]:
new = np.random.random((5,5))
print(new)
print(new.shape)

In [ ]:
s1 = np.arange(0,10) 
print(s1)



#vector , matrix  & tensor 

In [65]:
vector = np.array([1,2,3])
print("vector : ",vector)

matrix = np.array([[1,2,3],
                   [4,5,None]])
#print("Matrix :\n",matrix)

tensor = np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]],
                   [[7,8],[9,10],[11,12]],[[13,14],[15,16],[17,18]]])
print("Tensor :\n",tensor)
print(tensor.shape)



vector :  [1 2 3]
Tensor :
 [[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[ 7  8]
  [ 9 10]
  [11 12]]

 [[13 14]
  [15 16]
  [17 18]]]
(4, 3, 2)


#array properties

In [3]:
arr = np.array([[1,2,3,4,5,6,7,8],[5,6,7,8,9,10,11,12]])
print("Array :\n",arr)
print("shape : ",arr.shape)
print("Dimensions : ",arr.ndim)
print("Size  : ",arr.size)
print("Data Type : "  ,arr.dtype)
print("item Size : ",arr.itemsize)
print("Type : ",type(arr))
print("Reshape : ",arr.reshape(8,2))
print("Flattening : ",arr.flatten())# it works on the original array
print("Ravel: ",arr.ravel())# it works on a view or copy of the original array  
print("Transpose array : ",arr.T) 
print("Transpose array : ",arr.transpose())

Array :
 [[ 1  2  3  4  5  6  7  8]
 [ 5  6  7  8  9 10 11 12]]
shape :  (2, 8)
Dimensions :  2
Size  :  16
Data Type :  int64
item Size :  8
Type :  <class 'numpy.ndarray'>
Reshape :  [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Flattening :  [ 1  2  3  4  5  6  7  8  5  6  7  8  9 10 11 12]
Ravel:  [ 1  2  3  4  5  6  7  8  5  6  7  8  9 10 11 12]
Transpose array :  [[ 1  5]
 [ 2  6]
 [ 3  7]
 [ 4  8]
 [ 5  9]
 [ 6 10]
 [ 7 11]
 [ 8 12]]
Transpose array :  [[ 1  5]
 [ 2  6]
 [ 3  7]
 [ 4  8]
 [ 5  9]
 [ 6 10]
 [ 7 11]
 [ 8 12]]
